services:
  code-and-pepper-node-test:
    container_name: code-and-pepper-node-test
    image: node:22-alpine3.21
    working_dir: /app
    tty: true
    volumes:
      - code-and-pepper-node-test:/app
      - .:/app
    command: npm run test:e2e
    depends_on:
      - code-and-pepper-mongo-test

  code-and-pepper-mongo-test:
    container_name: code-and-pepper-mongo-test
    image: mongo:8.0.8
    tty: true
    ports:
      - 27027:27017
    volumes:
      - code-and-pepper-mongo-test:/data/db

volumes:
  code-and-pepper-node-test:
    name: code-and-pepper-node-test
  code-and-pepper-mongo-test:
    name: code-and-pepper-mongo-test
