services:
  node:
    container_name: code-and-pepper-node
    image: node:22-alpine3.21
    working_dir: /app
    tty: true
    ports:
      - 3000:3000
    volumes:
      - node:/app
      - .:/app
    command: npx nodemon
    depends_on:
      - mongo

  mongo:
    container_name: code-and-pepper-mongo
    image: mongo:8.0.8
    tty: true
    ports:
      - 27017:27017
    volumes:
      - mongo:/data/db

volumes:
  node:
    name: code-and-pepper-node
  mongo:
    name: code-and-pepper-mongo
