services:
  code-and-pepper-test-node:
    container_name: code-and-pepper-test-node
    image: node:22-alpine3.21
    working_dir: /app
    tty: true
    volumes:
      - code-and-pepper-test-node:/app
      - .:/app
    command: npm run test:e2e
    depends_on:
      - code-and-pepper-test-mongo

  code-and-pepper-test-mongo:
    container_name: code-and-pepper-test-mongo
    image: mongo:8.0.8
    tty: true
    ports:
      - 27027:27017
    volumes:
      - code-and-pepper-test-mongo:/data/db
      - ./mongo-init.sh:/mongo-init.sh
    entrypoint: /mongo-init.sh

volumes:
  code-and-pepper-test-node:
    name: code-and-pepper-test-node
  code-and-pepper-test-mongo:
    name: code-and-pepper-test-mongo
